// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqBRnbQrbqz7cJnMB7gS5d6muQEusuth4',
    appId: '1:39981715851:web:720f3bcdacf47397205f8e',
    messagingSenderId: '39981715851',
    projectId: 'km-emergency-comms',
    authDomain: 'km-emergency-comms.firebaseapp.com',
    storageBucket: 'km-emergency-comms.firebasestorage.app',
    measurementId: 'G-M2QYK7QR6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqr_39nHB6L0-gNHj2riMheQNGxVRdc8U',
    appId: '1:39981715851:android:13304bce4fe08cbb205f8e',
    messagingSenderId: '39981715851',
    projectId: 'km-emergency-comms',
    storageBucket: 'km-emergency-comms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgEgf9KMoXcy878zwvxQi3-wt-MuHA1Cg',
    appId: '1:39981715851:ios:156f2ed79dc849bf205f8e',
    messagingSenderId: '39981715851',
    projectId: 'km-emergency-comms',
    storageBucket: 'km-emergency-comms.firebasestorage.app',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgEgf9KMoXcy878zwvxQi3-wt-MuHA1Cg',
    appId: '1:39981715851:ios:156f2ed79dc849bf205f8e',
    messagingSenderId: '39981715851',
    projectId: 'km-emergency-comms',
    storageBucket: 'km-emergency-comms.firebasestorage.app',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqBRnbQrbqz7cJnMB7gS5d6muQEusuth4',
    appId: '1:39981715851:web:62ba894b92980cec205f8e',
    messagingSenderId: '39981715851',
    projectId: 'km-emergency-comms',
    authDomain: 'km-emergency-comms.firebaseapp.com',
    storageBucket: 'km-emergency-comms.firebasestorage.app',
    measurementId: 'G-P3PQ5VGQYL',
  );
}
